# %% [markdown]
# # Depthformer: Hierarchical Audio Token Generation
#
# This example builds a [Moshi](https://github.com/kyutai-labs/moshi)-style
# **Depthformer** using MLX SequenceLayers. The Depthformer generates audio
# tokens hierarchically across RVQ (Residual Vector Quantization) codebook
# levels.
#
# ## Architecture
#
# ```
# Text + Audio Embeddings (summed)
#     |
# Main Transformer (causal, RoPE, SwiGLU)
#     | RMSNorm
#     |---> Text Head --> text logits
#     \---> Depth Generation Loop
#              for slice_i in [0..3]:
#                x = project(main_out) + embed(prev_token)
#                y = depth_transformer.step(x)   <-- shared weights
#                logits = project(y) --> sample token
#              --> 4 audio codebook tokens
# ```
#
# The **main transformer** is a standard causal decoder with RoPE and
# SwiGLU gating. It processes the sum of text + audio embeddings along
# the time dimension.
#
# The **depth transformer** processes the "depth" dimension (codebook
# levels), not time. At each main-transformer step, it autoregressively
# generates one token per codebook level, conditioned on the main
# transformer output and all previous codebook levels. Its KV cache
# resets between time steps.
#
# **Requires:** `pip install sequence-layers[mlx]`

# %% [markdown]
# ## 1. Setup

# %%
import jax.nn
import mlx.core as mx
import mlx.nn as nn
import mlx.utils

import sequence_layers.jax as sl
from sequence_layers.mlx import basic_types as bt
from sequence_layers.mlx import export

Sequence = bt.Sequence
ShapeDType = bt.ShapeDType

# --- Hyperparameters (toy-sized for fast execution) ---

# Main transformer: processes text + audio along time.
MAIN_DIM = 128
MAIN_HEADS = 4
MAIN_UPH = MAIN_DIM // MAIN_HEADS  # 32
MAIN_LAYERS = 4
MAIN_HIDDEN = MAIN_DIM * 2  # 256 (SwiGLU intermediate)
MAIN_CONTEXT = 128

# Depth transformer: generates audio codebooks along depth.
DEPTH_DIM = 64
DEPTH_HEADS = 4
DEPTH_UPH = DEPTH_DIM // DEPTH_HEADS  # 16
DEPTH_LAYERS = 2
DEPTH_HIDDEN = DEPTH_DIM * 2  # 128

# Vocabulary.
TEXT_VOCAB = 256
AUDIO_VOCAB = 256
NUM_AUDIO_CODEBOOKS = 8  # total codebooks
NUM_DEPTH_SLICES = 4  # generated by depth transformer
NUM_INPUT_CODEBOOKS = NUM_AUDIO_CODEBOOKS - NUM_DEPTH_SLICES  # from input

# Generation.
BATCH_SIZE = 1
NUM_TOKENS = 16

print(
    f'Main transformer:  dim={MAIN_DIM}, heads={MAIN_HEADS}, '
    f'layers={MAIN_LAYERS}, hidden={MAIN_HIDDEN}, context={MAIN_CONTEXT}'
)
print(
    f'Depth transformer: dim={DEPTH_DIM}, heads={DEPTH_HEADS}, '
    f'layers={DEPTH_LAYERS}, hidden={DEPTH_HIDDEN}, '
    f'slices={NUM_DEPTH_SLICES}'
)
print(
    f'Vocab: text={TEXT_VOCAB}, audio={AUDIO_VOCAB}, '
    f'codebooks={NUM_AUDIO_CODEBOOKS} ({NUM_DEPTH_SLICES} generated + '
    f'{NUM_INPUT_CODEBOOKS} input)'
)

# %% [markdown]
# ## 2. Architecture Configs
#
# Both transformers use pre-norm residual blocks with SwiGLU gated FFN.
# The main transformer has RoPE positional encoding; the depth transformer
# has **none** (the codebook ordering is fixed and learned implicitly).
#
# Each transformer block:
# ```
# x + Flatten(SelfAttention(RMSNorm(x)))     <-- attention residual
# x + Dense(GatedUnit(Dense(RMSNorm(x))))    <-- SwiGLU FFN residual
# ```


# %%
def main_transformer_config():
  """Main causal transformer stack with RoPE and SwiGLU."""
  return sl.Repeat.Config(
      num_repeats=MAIN_LAYERS,
      layer=sl.Serial.Config([
          # Self-attention residual block.
          sl.Residual.Config([
              sl.RMSNormalization.Config(),
              sl.DotProductSelfAttention.Config(
                  num_heads=MAIN_HEADS,
                  units_per_head=MAIN_UPH,
                  max_past_horizon=MAIN_CONTEXT,
                  max_future_horizon=0,
                  query_network=sl.ApplyRotaryPositionalEncoding.Config(
                      max_wavelength=10_000.0,
                  ),
                  key_network=sl.ApplyRotaryPositionalEncoding.Config(
                      max_wavelength=10_000.0,
                  ),
              ),
              sl.Flatten.Config(),
          ]),
          # SwiGLU FFN residual block.
          sl.Residual.Config([
              sl.RMSNormalization.Config(),
              sl.Dense.Config(features=2 * MAIN_HIDDEN, use_bias=False),
              sl.GatedUnit.Config(
                  feature_activation=jax.nn.silu,
                  gate_activation=None,
              ),
              sl.Dense.Config(features=MAIN_DIM, use_bias=False),
          ]),
      ]),
  )


def depth_transformer_config():
  """Depth transformer stack: no positional encoding, small context."""
  return sl.Repeat.Config(
      num_repeats=DEPTH_LAYERS,
      layer=sl.Serial.Config([
          sl.Residual.Config([
              sl.RMSNormalization.Config(),
              sl.DotProductSelfAttention.Config(
                  num_heads=DEPTH_HEADS,
                  units_per_head=DEPTH_UPH,
                  max_past_horizon=NUM_DEPTH_SLICES,
                  max_future_horizon=0,
                  # No positional encoding for depth!
              ),
              sl.Flatten.Config(),
          ]),
          sl.Residual.Config([
              sl.RMSNormalization.Config(),
              sl.Dense.Config(features=2 * DEPTH_HIDDEN, use_bias=False),
              sl.GatedUnit.Config(
                  feature_activation=jax.nn.silu,
                  gate_activation=None,
              ),
              sl.Dense.Config(features=DEPTH_DIM, use_bias=False),
          ]),
      ]),
  )


main_config = main_transformer_config()
depth_config = depth_transformer_config()
print('Configs defined.')

# %% [markdown]
# ## 3. Model Definition
#
# The `Depthformer` wraps two sequence-layers models (main + depth
# transformer stacks) with multi-modal embeddings and the depth
# generation loop. SequenceLayers handles KV caching, step/layer
# duality, and state management automatically.

# %%


class DepthSlice(nn.Module):
  """Per-codebook components: embedding, input/output projections.

  Each depth slice has:
    - emb: embeds the previous slice's token (or text token for slice 0)
    - linear_in: projects main transformer output to depth dimension
    - linear_out: projects depth output to audio vocabulary logits
  """

  def __init__(self, in_vocab_size, out_vocab_size, main_dim, depth_dim):
    super().__init__()
    self.emb = nn.Embedding(in_vocab_size, depth_dim)
    self.linear_in = nn.Linear(main_dim, depth_dim, bias=False)
    self.linear_out = nn.Linear(depth_dim, out_vocab_size, bias=False)


class Depthformer(nn.Module):
  """Moshi-style Depthformer: main transformer + depth generation.

  The main transformer processes combined text + audio embeddings along
  the time dimension. The depth transformer generates audio tokens
  hierarchically across codebook levels, conditioned on the main
  transformer output.

  At each time step:
    1. Sum text + audio embeddings
    2. Step the main transformer (updates KV cache)
    3. Predict next text token
    4. Run depth generation: for each codebook slice, step the depth
       transformer (shared weights, accumulating KV cache), and sample
       the next audio token conditioned on previous slices.
    5. Reset depth KV cache (depth context doesn't persist across time)
  """

  def __init__(
      self,
      main_stack,
      depth_stack,
      main_dim,
      depth_dim,
      text_vocab,
      audio_vocab,
      num_codebooks,
      num_slices,
  ):
    super().__init__()
    self.main_stack = main_stack
    self.depth_stack = depth_stack
    self.text_emb = nn.Embedding(text_vocab, main_dim)
    self.audio_embs = [
        nn.Embedding(audio_vocab, main_dim) for _ in range(num_codebooks)
    ]
    self.out_norm = nn.RMSNorm(main_dim)
    self.text_head = nn.Linear(main_dim, text_vocab, bias=False)

    # Depth slices: first slice conditions on text, rest on audio.
    self.slices = []
    for i in range(num_slices):
      in_vocab = text_vocab if i == 0 else audio_vocab
      self.slices.append(DepthSlice(in_vocab, audio_vocab, main_dim, depth_dim))

    self._main_dim = main_dim
    self._depth_dim = depth_dim

  def _embed(self, text_token, audio_tokens):
    """Sum text + audio embeddings -> [batch, time, main_dim]."""
    x = self.text_emb(text_token)
    for tok, emb in zip(audio_tokens, self.audio_embs):
      x = x + emb(tok)
    return x

  def __call__(self, text_tokens, audio_tokens_list):
    """Layer mode: full sequence through the main transformer.

    Args:
      text_tokens: [batch, time] int32.
      audio_tokens_list: list of num_codebooks [batch, time] arrays.

    Returns:
      text_logits: [batch, time, text_vocab].
      hidden: [batch, time, main_dim].
    """
    x = self._embed(text_tokens, audio_tokens_list)
    mask = mx.ones(x.shape[:2], dtype=mx.bool_)
    y = self.main_stack.layer(Sequence(x, mask))
    h = self.out_norm(y.values)
    text_logits = self.text_head(h)
    return text_logits, h

  def get_initial_main_state(self, batch_size):
    """Create initial state for the main transformer."""
    spec = ShapeDType((self._main_dim,), mx.float32)
    return self.main_stack.get_initial_state(batch_size, spec)

  def generate_step(self, text_token, audio_tokens, main_state):
    """One autoregressive step: main transformer + depth generation.

    Args:
      text_token: [batch, 1] int32.
      audio_tokens: list of num_codebooks [batch, 1] int32 arrays.
      main_state: main transformer KV cache state.

    Returns:
      next_text: [batch, 1] int32.
      next_audio: list of num_slices [batch, 1] int32 arrays.
      new_main_state: updated main transformer state.
    """
    # --- Main transformer step ---
    x = self._embed(text_token, audio_tokens)
    mask = mx.ones((x.shape[0], 1), dtype=mx.bool_)
    y, main_state = self.main_stack.step(Sequence(x, mask), main_state)
    h = self.out_norm(y.values)  # [batch, 1, main_dim]

    # Text prediction.
    text_logits = self.text_head(h)
    next_text = mx.argmax(text_logits[:, 0, :], axis=-1, keepdims=True)

    # --- Depth generation ---
    # Fresh KV cache for each time step (depth context = codebook levels).
    depth_spec = ShapeDType((self._depth_dim,), mx.float32)
    depth_state = self.depth_stack.get_initial_state(x.shape[0], depth_spec)

    prev_token = next_text  # First slice conditions on text token.
    next_audio = []

    for s in self.slices:
      # Combine main output projection + previous token embedding.
      dx = s.linear_in(h) + s.emb(prev_token)

      # Step the shared depth transformer (accumulates KV cache).
      dy, depth_state = self.depth_stack.step(Sequence(dx, mask), depth_state)

      # Sample next audio token.
      logits = s.linear_out(dy.values)
      prev_token = mx.argmax(logits[:, 0, :], axis=-1, keepdims=True)
      next_audio.append(prev_token)

    return next_text, next_audio, main_state


# Build sequence-layers transformer stacks from configs.
main_stack = main_config.make(backend='mlx')
depth_stack = depth_config.make(backend='mlx')

model = Depthformer(
    main_stack,
    depth_stack,
    main_dim=MAIN_DIM,
    depth_dim=DEPTH_DIM,
    text_vocab=TEXT_VOCAB,
    audio_vocab=AUDIO_VOCAB,
    num_codebooks=NUM_AUDIO_CODEBOOKS,
    num_slices=NUM_DEPTH_SLICES,
)

# Materialize deferred layers (attention needs to know in_features).
main_input_spec = ShapeDType((MAIN_DIM,), mx.float32)
depth_input_spec = ShapeDType((DEPTH_DIM,), mx.float32)
export._materialize_deferred(model.main_stack, BATCH_SIZE, main_input_spec)
export._materialize_deferred(model.depth_stack, BATCH_SIZE, depth_input_spec)

# Count parameters.
nparams = sum(v.size for _, v in mlx.utils.tree_flatten(model.parameters()))
print(f'Model built: {nparams:,} parameters')

# %% [markdown]
# ## 4. Layer Mode
#
# Process a full sequence through the main transformer. This is useful
# for teacher forcing (training) or batch inference on prefilled context.

# %%
seq_len = 8

# Random input tokens.
text_tokens = mx.random.randint(0, TEXT_VOCAB, shape=(BATCH_SIZE, seq_len))
audio_tokens_list = [
    mx.random.randint(0, AUDIO_VOCAB, shape=(BATCH_SIZE, seq_len))
    for _ in range(NUM_AUDIO_CODEBOOKS)
]

text_logits, hidden = model(text_tokens, audio_tokens_list)
mx.eval(text_logits, hidden)

print(
    f'Input:       text {text_tokens.shape}, '
    f'audio {len(audio_tokens_list)}x{audio_tokens_list[0].shape}'
)
print(f'Text logits: {text_logits.shape}')
print(f'Hidden:      {hidden.shape}')

# %% [markdown]
# ## 5. Streaming Generation
#
# Token-by-token autoregressive generation. At each step:
# 1. The main transformer processes the current token (KV cache persists)
# 2. The depth transformer generates audio tokens across codebook levels
#    (KV cache resets per time step)
# 3. Generated audio tokens feed back as input at the next time step

# %%
# Initialize state.
main_state = model.get_initial_main_state(BATCH_SIZE)

# Start with zero tokens (padding / start-of-sequence).
text_token = mx.zeros((BATCH_SIZE, 1), dtype=mx.int32)
audio_tokens = [
    mx.zeros((BATCH_SIZE, 1), dtype=mx.int32)
    for _ in range(NUM_AUDIO_CODEBOOKS)
]

generated_text = []
generated_audio = [[] for _ in range(NUM_DEPTH_SLICES)]

print(f'Generating {NUM_TOKENS} steps...\n')

for t in range(NUM_TOKENS):
  next_text, next_audio, main_state = model.generate_step(
      text_token, audio_tokens, main_state
  )
  mx.eval(next_text, *next_audio)

  # Record generated tokens.
  generated_text.append(int(next_text[0, 0]))
  for i in range(NUM_DEPTH_SLICES):
    generated_audio[i].append(int(next_audio[i][0, 0]))

  # Prepare next input.
  text_token = next_text
  for i in range(NUM_DEPTH_SLICES):
    audio_tokens[i] = next_audio[i]
  # Input codebooks stay zero (no "environment" audio in this demo).

print(f'Text tokens:    {generated_text}')
for i in range(NUM_DEPTH_SLICES):
  print(f'Audio cb {i}:     {generated_audio[i]}')

# %% [markdown]
# ## 6. Why SequenceLayers?
#
# Compare the Moshi codebase (~1000 lines of handwritten transformer,
# attention, KV cache, and streaming code) with the SequenceLayers
# approach:
#
# | Aspect | Moshi (handwritten) | SequenceLayers |
# |--------|-------------------|----------------|
# | Transformer | `Transformer`, `TransformerLayer`, `Attention`, `MlpGating` classes | `Repeat(Serial(Residual(Norm, Attn, Flatten), Residual(Norm, Dense, GatedUnit, Dense)))` config |
# | KV cache | Manual `KVCache`, `RotatingKVCache` classes + explicit offset tracking | Automatic via `step()` — ring buffer with `put_along_axis` |
# | Streaming | Custom `__call__` with cache threading | `model.step(x, state)` returns updated state |
# | Layer / Step | Separate code paths | `layer()` and `step()` from one config, verified equivalent |
# | Positional encoding | Separate `nn.RoPE` object, manually applied | `query_network=ApplyRotaryPositionalEncoding.Config(...)` |
# | Export | N/A | `export.export_step(model, path, ...)` → `.mlxfn` |
#
# The model-specific code (embeddings, depth generation loop) stays
# custom, while the transformer building blocks come from SequenceLayers
# with all the streaming, caching, and state management handled
# automatically.

# %%
print('Done!')
